# Generated by Django 4.2.7 on 2023-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
