# Generated by Django 4.2.7 on 2023-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_position_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
