# Generated by Django 4.2.7 on 2023-11-28 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_position_ag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='ag',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
