# Generated by Django 4.2.7 on 2023-11-30 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_memberteam_player_qty_memberteam_reroll_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberteam',
            name='apothecary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='assistant_coaches',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='cheerleaders',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='current_team_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='dedicated_fans',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='treasury',
            field=models.IntegerField(default=0),
        ),
    ]
