# Generated by Django 4.2.7 on 2023-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_memberteam_apothecary_memberteam_assistant_coaches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberteam',
            name='league_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='total_casualties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberteam',
            name='total_touchdowns',
            field=models.IntegerField(default=0),
        ),
    ]
