# Generated by Django 4.2.7 on 2023-11-30 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_memberteam_league_points_memberteam_total_casualties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
